# Generated by Django 5.0.7 on 2024-07-27 10:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Car',
            fields=[
                ('cid', models.IntegerField(primary_key=True, serialize=False)),
                ('c_name', models.CharField(max_length=23)),
                ('c_no', models.BigIntegerField()),
                ('numberplate', models.IntegerField()),
                ('datefrom', models.DateField()),
                ('dateto', models.DateField()),
                ('rate', models.CharField(choices=[('1day=500', '1day=500'), ('2day=1000', '2day=1000')], max_length=23)),
                ('gender', models.CharField(choices=[('female', 'femlae'), ('male', 'male')], max_length=23)),
            ],
        ),
    ]
